server:
  port: 8081
  
app:
  prime:
    additionalMemoryLoad: false
    array:
      size:
        max: 500
    thread:
      pool:
        size: 10

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

