server:
  port: 8081
  
app:
  prime:
    array:
      size:
        max: 500
    thread:
      pool:
        size: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workload?currentSchema:prime
    username: workload
    password: abc123
  jpa:
    properties:
      hibernate:
        default_schema: prime

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

